# -*- coding: utf-8 -*-
"""cov-jp_2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1he0z-aJvys5FGIX62I2K-PW8rax0O0R1
"""

import pandas as pd
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
import numpy as np
from google.colab import drive
drive.mount('/content/drive')
# Load the datasets
vaccination_data = pd.read_csv('/content/drive/MyDrive/colabnotebooks/yearly_vaccination_totals.csv')
confirmed_cases_data = pd.read_csv('/content/drive/MyDrive/colabnotebooks/yearly_confirmed_cases.csv')
economic_data = pd.read_csv('/content/drive/MyDrive/colabnotebooks/reshaped_economic_data.csv')

# Identify and remove duplicates in the economic data
economic_data = economic_data.drop_duplicates(subset=['Year', 'Series Name'])

# Pivot the economic data to have one column for each 'Series Name'
economic_data_pivot = economic_data.pivot(index='Year', columns='Series Name', values='Value').reset_index()

# Merging the datasets based on 'Year'
merged_data = pd.merge(pd.merge(vaccination_data, confirmed_cases_data, on='Year'), economic_data_pivot, on='Year')

# Handling missing values: Replace ".." with NaN and then use forward fill for simplicity
merged_data.replace('..', np.nan, inplace=True)
merged_data = merged_data.ffill()

# Convert all columns to numeric where applicable
merged_data = merged_data.apply(pd.to_numeric, errors='ignore')

# Filter data for the years 2020 to 2023
filtered_data = merged_data[(merged_data['Year'] >= 2020) & (merged_data['Year'] <= 2023)]

# Prepare data for comparison plots
unemployment_rate = filtered_data['Unemployment, total (% of total labor force) (national estimate)']
gdp_growth_rate = filtered_data['GDP growth (annual %)']
confirmed_rate = filtered_data['ALL']  # Assuming 'ALL' represents the confirmed cases rate

# Plot 1: Actual Unemployment Rate vs. GDP Growth Rate (2020-2023)
plt.figure(figsize=(14, 12))

plt.subplot(3, 1, 1)
plt.plot(filtered_data['Year'], unemployment_rate, marker='o', label='Unemployment Rate', color='blue')
plt.plot(filtered_data['Year'], gdp_growth_rate, marker='x', linestyle='--', label='GDP Growth Rate', color='red')
plt.title('Actual Unemployment Rate vs. GDP Growth Rate (2020-2023)')
plt.xlabel('Year')
plt.ylabel('Rate (%)')
plt.legend()
plt.grid(True)

# Plot 2: Actual GDP Growth Rate vs. Confirmed Rate (2020-2023)
plt.subplot(3, 1, 2)
plt.plot(filtered_data['Year'], gdp_growth_rate, marker='o', label='GDP Growth Rate', color='blue')
plt.plot(filtered_data['Year'], confirmed_rate, marker='x', linestyle='--', label='Confirmed Rate', color='green')
plt.title('Actual GDP Growth Rate vs. Confirmed Rate (2020-2023)')
plt.xlabel('Year')
plt.ylabel('Rate')
plt.legend()
plt.grid(True)

# Plot 3: Actual Unemployment Rate vs. Confirmed Rate (2020-2023)
plt.subplot(3, 1, 3)
plt.plot(filtered_data['Year'], unemployment_rate, marker='o', label='Unemployment Rate', color='blue')
plt.plot(filtered_data['Year'], confirmed_rate, marker='x', linestyle='--', label='Confirmed Rate', color='purple')
plt.title('Actual Unemployment Rate vs. Confirmed Rate (2020-2023)')
plt.xlabel('Year')
plt.ylabel('Rate')
plt.legend()
plt.grid(True)

plt.tight_layout()
plt.show()

# Prepare the model for prediction (using 2020-2023 data)
X = filtered_data[['Unemployment, total (% of total labor force) (national estimate)', 'ALL']]
y = gdp_growth_rate

model = LinearRegression()
model.fit(X, y)

# Predicting GDP growth rate, unemployment rate, and confirmed rate for future years (2024-2026)
future_unemployment_rates = np.array([2.5, 2.6, 2.7])  # Example future values
future_confirmed_rates = np.array([1e6, 1.1e6, 1.2e6])  # Example future values, replace with realistic data

future_data = pd.DataFrame({
    'Unemployment, total (% of total labor force) (national estimate)': future_unemployment_rates,
    'ALL': future_confirmed_rates
})

gdp_forecasts = model.predict(future_data)

# Displaying the predicted results
predicted_df = pd.DataFrame({
    'Year': [2024, 2025, 2026],
    'Predicted GDP Growth Rate': gdp_forecasts,
    'Predicted Unemployment Rate': future_unemployment_rates,
    'Predicted Confirmed Rate': future_confirmed_rates
})

print("Predicted values for 2024-2026:")
print(predicted_df)

# Plotting the predictions in two groups

# Group 1: Predicted GDP Growth Rate and Unemployment Rate
plt.figure(figsize=(14, 6))

plt.subplot(2, 1, 1)
plt.plot(predicted_df['Year'], predicted_df['Predicted GDP Growth Rate'], marker='o', linestyle='-', label='Predicted GDP Growth Rate', color='red')
plt.plot(predicted_df['Year'], predicted_df['Predicted Unemployment Rate'], marker='x', linestyle='--', label='Predicted Unemployment Rate', color='blue')
plt.title('Predicted GDP Growth Rate and Unemployment Rate (2024-2026)')
plt.xlabel('Year')
plt.ylabel('Rate (%)')
plt.legend()
plt.grid(True)

# Group 2: Predicted Confirmed Rate
plt.subplot(2, 1, 2)
plt.plot(predicted_df['Year'], predicted_df['Predicted Confirmed Rate'], marker='s', linestyle='--', label='Predicted Confirmed Rate', color='green')
plt.title('Predicted Confirmed Case Rate (2024-2026)')
plt.xlabel('Year')
plt.ylabel('Confirmed Rate')
plt.legend()
plt.grid(True)

plt.tight_layout()
plt.show()